var TREE_ITEMS = [
['TOP', './index.html', ['admin', 'admin/index.html', ['backups', 'admin/backups/index.html', ['index.html', 'admin/backups/index.html.html']
]
, ['inc', 'admin/inc/index.html', ['class_form.php', 'admin/inc/class_form.php.html']
, ['class_page.php', 'admin/inc/class_page.php.html']
, ['class_table.php', 'admin/inc/class_table.php.html']
, ['functions.php', 'admin/inc/functions.php.html']
, ['functions_themes.php', 'admin/inc/functions_themes.php.html']
, ['functions_view_manager.php', 'admin/inc/functions_view_manager.php.html']
, ['index.html', 'admin/inc/index.html.html']
]
, ['jscripts', 'admin/jscripts/index.html', ['codepress', 'admin/jscripts/codepress/index.html', ['engines', 'admin/jscripts/codepress/engines/index.html', ['gecko.js', 'admin/jscripts/codepress/engines/gecko.js.html']
, ['khtml.js', 'admin/jscripts/codepress/engines/khtml.js.html']
, ['msie.js', 'admin/jscripts/codepress/engines/msie.js.html']
, ['older.js', 'admin/jscripts/codepress/engines/older.js.html']
, ['opera.js', 'admin/jscripts/codepress/engines/opera.js.html']
]
, ['images', 'admin/jscripts/codepress/images/index.html']
, ['languages', 'admin/jscripts/codepress/languages/index.html', ['autoit.css', 'admin/jscripts/codepress/languages/autoit.css.html']
, ['autoit.js', 'admin/jscripts/codepress/languages/autoit.js.html']
, ['codepress-mybb.css', 'admin/jscripts/codepress/languages/codepress-mybb.css.html']
, ['css.css', 'admin/jscripts/codepress/languages/css.css.html']
, ['css.js', 'admin/jscripts/codepress/languages/css.js.html']
, ['generic.css', 'admin/jscripts/codepress/languages/generic.css.html']
, ['generic.js', 'admin/jscripts/codepress/languages/generic.js.html']
, ['html.css', 'admin/jscripts/codepress/languages/html.css.html']
, ['html.js', 'admin/jscripts/codepress/languages/html.js.html']
, ['javascript.css', 'admin/jscripts/codepress/languages/javascript.css.html']
, ['javascript.js', 'admin/jscripts/codepress/languages/javascript.js.html']
, ['mybb.css', 'admin/jscripts/codepress/languages/mybb.css.html']
, ['mybb.js', 'admin/jscripts/codepress/languages/mybb.js.html']
, ['php.css', 'admin/jscripts/codepress/languages/php.css.html']
, ['php.js', 'admin/jscripts/codepress/languages/php.js.html']
, ['text.css', 'admin/jscripts/codepress/languages/text.css.html']
, ['text.js', 'admin/jscripts/codepress/languages/text.js.html']
]
, ['codepress.css', 'admin/jscripts/codepress/codepress.css.html']
, ['codepress.html', 'admin/jscripts/codepress/codepress.html.html']
, ['codepress.js', 'admin/jscripts/codepress/codepress.js.html']
, ['license.txt', 'admin/jscripts/codepress/license.txt.html']
]
, ['admincp.js', 'admin/jscripts/admincp.js.html']
, ['imodal.js', 'admin/jscripts/imodal.js.html']
, ['index.html', 'admin/jscripts/index.html.html']
, ['mycode_sandbox.js', 'admin/jscripts/mycode_sandbox.js.html']
, ['peeker.js', 'admin/jscripts/peeker.js.html']
, ['quick_perm_editor.js', 'admin/jscripts/quick_perm_editor.js.html']
, ['tabs.js', 'admin/jscripts/tabs.js.html']
, ['themes.js', 'admin/jscripts/themes.js.html']
, ['users.js', 'admin/jscripts/users.js.html']
, ['view_manager.js', 'admin/jscripts/view_manager.js.html']
]
, ['modules', 'admin/modules/index.html', ['config', 'admin/modules/config/index.html', ['attachment_types.php', 'admin/modules/config/attachment_types.php.html']
, ['badwords.php', 'admin/modules/config/badwords.php.html']
, ['banning.php', 'admin/modules/config/banning.php.html']
, ['calendars.php', 'admin/modules/config/calendars.php.html']
, ['help_documents.php', 'admin/modules/config/help_documents.php.html']
, ['index.html', 'admin/modules/config/index.html.html']
, ['languages.php', 'admin/modules/config/languages.php.html']
, ['mod_tools.php', 'admin/modules/config/mod_tools.php.html']
, ['module_meta.php', 'admin/modules/config/module_meta.php.html']
, ['mycode.php', 'admin/modules/config/mycode.php.html']
, ['plugins.php', 'admin/modules/config/plugins.php.html']
, ['post_icons.php', 'admin/modules/config/post_icons.php.html']
, ['profile_fields.php', 'admin/modules/config/profile_fields.php.html']
, ['settings.php', 'admin/modules/config/settings.php.html']
, ['smilies.php', 'admin/modules/config/smilies.php.html']
, ['spiders.php', 'admin/modules/config/spiders.php.html']
, ['thread_prefixes.php', 'admin/modules/config/thread_prefixes.php.html']
, ['warning.php', 'admin/modules/config/warning.php.html']
]
, ['forum', 'admin/modules/forum/index.html', ['announcements.php', 'admin/modules/forum/announcements.php.html']
, ['attachments.php', 'admin/modules/forum/attachments.php.html']
, ['index.html', 'admin/modules/forum/index.html.html']
, ['management.php', 'admin/modules/forum/management.php.html']
, ['moderation_queue.php', 'admin/modules/forum/moderation_queue.php.html']
, ['module_meta.php', 'admin/modules/forum/module_meta.php.html']
]
, ['home', 'admin/modules/home/index.html', ['credits.php', 'admin/modules/home/credits.php.html']
, ['index.html', 'admin/modules/home/index.html.html']
, ['index.php', 'admin/modules/home/index.php.html']
, ['module_meta.php', 'admin/modules/home/module_meta.php.html']
, ['preferences.php', 'admin/modules/home/preferences.php.html']
, ['version_check.php', 'admin/modules/home/version_check.php.html']
]
, ['style', 'admin/modules/style/index.html', ['index.html', 'admin/modules/style/index.html.html']
, ['module_meta.php', 'admin/modules/style/module_meta.php.html']
, ['templates.php', 'admin/modules/style/templates.php.html']
, ['themes.php', 'admin/modules/style/themes.php.html']
]
, ['tools', 'admin/modules/tools/index.html', ['adminlog.php', 'admin/modules/tools/adminlog.php.html']
, ['backupdb.php', 'admin/modules/tools/backupdb.php.html']
, ['cache.php', 'admin/modules/tools/cache.php.html']
, ['file_verification.php', 'admin/modules/tools/file_verification.php.html']
, ['index.html', 'admin/modules/tools/index.html.html']
, ['mailerrors.php', 'admin/modules/tools/mailerrors.php.html']
, ['maillogs.php', 'admin/modules/tools/maillogs.php.html']
, ['modlog.php', 'admin/modules/tools/modlog.php.html']
, ['module_meta.php', 'admin/modules/tools/module_meta.php.html']
, ['optimizedb.php', 'admin/modules/tools/optimizedb.php.html']
, ['php_info.php', 'admin/modules/tools/php_info.php.html']
, ['recount_rebuild.php', 'admin/modules/tools/recount_rebuild.php.html']
, ['statistics.php', 'admin/modules/tools/statistics.php.html']
, ['system_health.php', 'admin/modules/tools/system_health.php.html']
, ['tasks.php', 'admin/modules/tools/tasks.php.html']
, ['warninglog.php', 'admin/modules/tools/warninglog.php.html']
]
, ['user', 'admin/modules/user/index.html', ['admin_permissions.php', 'admin/modules/user/admin_permissions.php.html']
, ['banning.php', 'admin/modules/user/banning.php.html']
, ['group_promotions.php', 'admin/modules/user/group_promotions.php.html']
, ['groups.php', 'admin/modules/user/groups.php.html']
, ['index.html', 'admin/modules/user/index.html.html']
, ['mass_mail.php', 'admin/modules/user/mass_mail.php.html']
, ['module_meta.php', 'admin/modules/user/module_meta.php.html']
, ['titles.php', 'admin/modules/user/titles.php.html']
, ['users.php', 'admin/modules/user/users.php.html']
]
, ['index.html', 'admin/modules/index.html.html']
]
, ['styles', 'admin/styles/index.html', ['default', 'admin/styles/default/index.html', ['images', 'admin/styles/default/images/index.html', ['icons', 'admin/styles/default/images/icons/index.html', ['index.html', 'admin/styles/default/images/icons/index.html.html']
]
, ['index.html', 'admin/styles/default/images/index.html.html']
]
, ['avatar_gallery.css', 'admin/styles/default/avatar_gallery.css.html']
, ['forum.css', 'admin/styles/default/forum.css.html']
, ['home.css', 'admin/styles/default/home.css.html']
, ['imodal.css', 'admin/styles/default/imodal.css.html']
, ['index.html', 'admin/styles/default/index.html.html']
, ['login.css', 'admin/styles/default/login.css.html']
, ['main.css', 'admin/styles/default/main.css.html']
, ['popup.css', 'admin/styles/default/popup.css.html']
, ['style.css', 'admin/styles/default/style.css.html']
, ['style.php', 'admin/styles/default/style.php.html']
, ['user.css', 'admin/styles/default/user.css.html']
]
, ['sharepoint', 'admin/styles/sharepoint/index.html', ['images', 'admin/styles/sharepoint/images/index.html', ['icons', 'admin/styles/sharepoint/images/icons/index.html', ['index.html', 'admin/styles/sharepoint/images/icons/index.html.html']
]
, ['index.html', 'admin/styles/sharepoint/images/index.html.html']
]
, ['avatar_gallery.css', 'admin/styles/sharepoint/avatar_gallery.css.html']
, ['home.css', 'admin/styles/sharepoint/home.css.html']
, ['index.html', 'admin/styles/sharepoint/index.html.html']
, ['login.css', 'admin/styles/sharepoint/login.css.html']
, ['main.css', 'admin/styles/sharepoint/main.css.html']
, ['popup.css', 'admin/styles/sharepoint/popup.css.html']
, ['style.css', 'admin/styles/sharepoint/style.css.html']
, ['style.php', 'admin/styles/sharepoint/style.php.html']
, ['user.css', 'admin/styles/sharepoint/user.css.html']
]
, ['index.html', 'admin/styles/index.html.html']
]
, ['index.php', 'admin/index.php.html']
]
, ['archive', 'archive/index.html', ['global.php', 'archive/global.php.html']
, ['index.php', 'archive/index.php.html']
, ['print.css', 'archive/print.css.html']
, ['screen.css', 'archive/screen.css.html']
]
, ['cache', 'cache/index.html', ['themes', 'cache/themes/index.html', ['index.html', 'cache/themes/index.html.html']
]
, ['index.html', 'cache/index.html.html']
]
, ['images', 'images/index.html', ['attachtypes', 'images/attachtypes/index.html']
, ['avatars', 'images/avatars/index.html']
, ['codebuttons', 'images/codebuttons/index.html']
, ['english', 'images/english/index.html']
, ['groupimages', 'images/groupimages/index.html', ['english', 'images/groupimages/english/index.html']
]
, ['icons', 'images/icons/index.html']
, ['modcp', 'images/modcp/index.html']
, ['smilies', 'images/smilies/index.html']
, ['toplinks', 'images/toplinks/index.html']
, ['usercp', 'images/usercp/index.html']
, ['index.html', 'images/index.html.html']
]
, ['inc', 'inc/index.html', ['3rdparty', 'inc/3rdparty/index.html', ['diff', 'inc/3rdparty/diff/index.html', ['Diff', 'inc/3rdparty/diff/Diff/index.html', ['Engine', 'inc/3rdparty/diff/Diff/Engine/index.html', ['index.html', 'inc/3rdparty/diff/Diff/Engine/index.html.html']
, ['native.php', 'inc/3rdparty/diff/Diff/Engine/native.php.html']
, ['shell.php', 'inc/3rdparty/diff/Diff/Engine/shell.php.html']
, ['string.php', 'inc/3rdparty/diff/Diff/Engine/string.php.html']
, ['xdiff.php', 'inc/3rdparty/diff/Diff/Engine/xdiff.php.html']
]
, ['Renderer', 'inc/3rdparty/diff/Diff/Renderer/index.html', ['index.html', 'inc/3rdparty/diff/Diff/Renderer/index.html.html']
, ['inline.php', 'inc/3rdparty/diff/Diff/Renderer/inline.php.html']
, ['unified.php', 'inc/3rdparty/diff/Diff/Renderer/unified.php.html']
]
, ['Mapped.php', 'inc/3rdparty/diff/Diff/Mapped.php.html']
, ['Renderer.php', 'inc/3rdparty/diff/Diff/Renderer.php.html']
, ['ThreeWay.php', 'inc/3rdparty/diff/Diff/ThreeWay.php.html']
, ['index.html', 'inc/3rdparty/diff/Diff/index.html.html']
]
, ['Diff.php', 'inc/3rdparty/diff/Diff.php.html']
, ['Diff3.php', 'inc/3rdparty/diff/Diff3.php.html']
, ['index.html', 'inc/3rdparty/diff/index.html.html']
]
, ['index.html', 'inc/3rdparty/index.html.html']
]
, ['cachehandlers', 'inc/cachehandlers/index.html', ['disk.php', 'inc/cachehandlers/disk.php.html']
, ['eaccelerator.php', 'inc/cachehandlers/eaccelerator.php.html']
, ['index.html', 'inc/cachehandlers/index.html.html']
, ['memcache.php', 'inc/cachehandlers/memcache.php.html']
, ['xcache.php', 'inc/cachehandlers/xcache.php.html']
]
, ['captcha_fonts', 'inc/captcha_fonts/index.html', ['index.html', 'inc/captcha_fonts/index.html.html']
, ['read_me.html', 'inc/captcha_fonts/read_me.html.html']
]
, ['datahandlers', 'inc/datahandlers/index.html', ['event.php', 'inc/datahandlers/event.php.html']
, ['index.html', 'inc/datahandlers/index.html.html']
, ['pm.php', 'inc/datahandlers/pm.php.html']
, ['post.php', 'inc/datahandlers/post.php.html']
, ['user.php', 'inc/datahandlers/user.php.html']
]
, ['languages', 'inc/languages/index.html', ['english', 'inc/languages/english/index.html', ['admin', 'inc/languages/english/admin/index.html', ['config_attachment_types.lang.php', 'inc/languages/english/admin/config_attachment_types.lang.php.html']
, ['config_badwords.lang.php', 'inc/languages/english/admin/config_badwords.lang.php.html']
, ['config_banning.lang.php', 'inc/languages/english/admin/config_banning.lang.php.html']
, ['config_calendars.lang.php', 'inc/languages/english/admin/config_calendars.lang.php.html']
, ['config_help_documents.lang.php', 'inc/languages/english/admin/config_help_documents.lang.php.html']
, ['config_languages.lang.php', 'inc/languages/english/admin/config_languages.lang.php.html']
, ['config_mod_tools.lang.php', 'inc/languages/english/admin/config_mod_tools.lang.php.html']
, ['config_module_meta.lang.php', 'inc/languages/english/admin/config_module_meta.lang.php.html']
, ['config_mycode.lang.php', 'inc/languages/english/admin/config_mycode.lang.php.html']
, ['config_plugins.lang.php', 'inc/languages/english/admin/config_plugins.lang.php.html']
, ['config_post_icons.lang.php', 'inc/languages/english/admin/config_post_icons.lang.php.html']
, ['config_profile_fields.lang.php', 'inc/languages/english/admin/config_profile_fields.lang.php.html']
, ['config_settings.lang.php', 'inc/languages/english/admin/config_settings.lang.php.html']
, ['config_smilies.lang.php', 'inc/languages/english/admin/config_smilies.lang.php.html']
, ['config_spiders.lang.php', 'inc/languages/english/admin/config_spiders.lang.php.html']
, ['config_thread_prefixes.lang.php', 'inc/languages/english/admin/config_thread_prefixes.lang.php.html']
, ['config_warning.lang.php', 'inc/languages/english/admin/config_warning.lang.php.html']
, ['forum_akismet.lang.php', 'inc/languages/english/admin/forum_akismet.lang.php.html']
, ['forum_announcements.lang.php', 'inc/languages/english/admin/forum_announcements.lang.php.html']
, ['forum_attachments.lang.php', 'inc/languages/english/admin/forum_attachments.lang.php.html']
, ['forum_management.lang.php', 'inc/languages/english/admin/forum_management.lang.php.html']
, ['forum_moderation_queue.lang.php', 'inc/languages/english/admin/forum_moderation_queue.lang.php.html']
, ['forum_module_meta.lang.php', 'inc/languages/english/admin/forum_module_meta.lang.php.html']
, ['global.lang.php', 'inc/languages/english/admin/global.lang.php.html']
, ['home_credits.lang.php', 'inc/languages/english/admin/home_credits.lang.php.html']
, ['home_dashboard.lang.php', 'inc/languages/english/admin/home_dashboard.lang.php.html']
, ['home_module_meta.lang.php', 'inc/languages/english/admin/home_module_meta.lang.php.html']
, ['home_preferences.lang.php', 'inc/languages/english/admin/home_preferences.lang.php.html']
, ['home_version_check.lang.php', 'inc/languages/english/admin/home_version_check.lang.php.html']
, ['index.html', 'inc/languages/english/admin/index.html.html']
, ['style_module_meta.lang.php', 'inc/languages/english/admin/style_module_meta.lang.php.html']
, ['style_templates.lang.php', 'inc/languages/english/admin/style_templates.lang.php.html']
, ['style_themes.lang.php', 'inc/languages/english/admin/style_themes.lang.php.html']
, ['tools_adminlog.lang.php', 'inc/languages/english/admin/tools_adminlog.lang.php.html']
, ['tools_backupdb.lang.php', 'inc/languages/english/admin/tools_backupdb.lang.php.html']
, ['tools_cache.lang.php', 'inc/languages/english/admin/tools_cache.lang.php.html']
, ['tools_file_verification.lang.php', 'inc/languages/english/admin/tools_file_verification.lang.php.html']
, ['tools_mailerrors.lang.php', 'inc/languages/english/admin/tools_mailerrors.lang.php.html']
, ['tools_maillogs.lang.php', 'inc/languages/english/admin/tools_maillogs.lang.php.html']
, ['tools_modlog.lang.php', 'inc/languages/english/admin/tools_modlog.lang.php.html']
, ['tools_module_meta.lang.php', 'inc/languages/english/admin/tools_module_meta.lang.php.html']
, ['tools_optimizedb.lang.php', 'inc/languages/english/admin/tools_optimizedb.lang.php.html']
, ['tools_php_info.lang.php', 'inc/languages/english/admin/tools_php_info.lang.php.html']
, ['tools_recount_rebuild.lang.php', 'inc/languages/english/admin/tools_recount_rebuild.lang.php.html']
, ['tools_statistics.lang.php', 'inc/languages/english/admin/tools_statistics.lang.php.html']
, ['tools_system_health.lang.php', 'inc/languages/english/admin/tools_system_health.lang.php.html']
, ['tools_tasks.lang.php', 'inc/languages/english/admin/tools_tasks.lang.php.html']
, ['tools_warninglog.lang.php', 'inc/languages/english/admin/tools_warninglog.lang.php.html']
, ['user_admin_permissions.lang.php', 'inc/languages/english/admin/user_admin_permissions.lang.php.html']
, ['user_banning.lang.php', 'inc/languages/english/admin/user_banning.lang.php.html']
, ['user_group_promotions.lang.php', 'inc/languages/english/admin/user_group_promotions.lang.php.html']
, ['user_groups.lang.php', 'inc/languages/english/admin/user_groups.lang.php.html']
, ['user_mass_mail.lang.php', 'inc/languages/english/admin/user_mass_mail.lang.php.html']
, ['user_module_meta.lang.php', 'inc/languages/english/admin/user_module_meta.lang.php.html']
, ['user_titles.lang.php', 'inc/languages/english/admin/user_titles.lang.php.html']
, ['user_users.lang.php', 'inc/languages/english/admin/user_users.lang.php.html']
]
, ['akismet.lang.php', 'inc/languages/english/akismet.lang.php.html']
, ['announcements.lang.php', 'inc/languages/english/announcements.lang.php.html']
, ['archive.lang.php', 'inc/languages/english/archive.lang.php.html']
, ['calendar.lang.php', 'inc/languages/english/calendar.lang.php.html']
, ['customhelpdocs.lang.php', 'inc/languages/english/customhelpdocs.lang.php.html']
, ['customhelpsections.lang.php', 'inc/languages/english/customhelpsections.lang.php.html']
, ['datahandler_event.lang.php', 'inc/languages/english/datahandler_event.lang.php.html']
, ['datahandler_pm.lang.php', 'inc/languages/english/datahandler_pm.lang.php.html']
, ['datahandler_post.lang.php', 'inc/languages/english/datahandler_post.lang.php.html']
, ['datahandler_user.lang.php', 'inc/languages/english/datahandler_user.lang.php.html']
, ['editpost.lang.php', 'inc/languages/english/editpost.lang.php.html']
, ['forumdisplay.lang.php', 'inc/languages/english/forumdisplay.lang.php.html']
, ['global.lang.php', 'inc/languages/english/global.lang.php.html']
, ['helpdocs.lang.php', 'inc/languages/english/helpdocs.lang.php.html']
, ['helpsections.lang.php', 'inc/languages/english/helpsections.lang.php.html']
, ['index.html', 'inc/languages/english/index.html.html']
, ['index.lang.php', 'inc/languages/english/index.lang.php.html']
, ['mailhandler.lang.php', 'inc/languages/english/mailhandler.lang.php.html']
, ['managegroup.lang.php', 'inc/languages/english/managegroup.lang.php.html']
, ['member.lang.php', 'inc/languages/english/member.lang.php.html']
, ['memberlist.lang.php', 'inc/languages/english/memberlist.lang.php.html']
, ['messages.lang.php', 'inc/languages/english/messages.lang.php.html']
, ['misc.lang.php', 'inc/languages/english/misc.lang.php.html']
, ['modcp.lang.php', 'inc/languages/english/modcp.lang.php.html']
, ['moderation.lang.php', 'inc/languages/english/moderation.lang.php.html']
, ['newreply.lang.php', 'inc/languages/english/newreply.lang.php.html']
, ['newthread.lang.php', 'inc/languages/english/newthread.lang.php.html']
, ['online.lang.php', 'inc/languages/english/online.lang.php.html']
, ['polls.lang.php', 'inc/languages/english/polls.lang.php.html']
, ['portal.lang.php', 'inc/languages/english/portal.lang.php.html']
, ['printthread.lang.php', 'inc/languages/english/printthread.lang.php.html']
, ['private.lang.php', 'inc/languages/english/private.lang.php.html']
, ['ratethread.lang.php', 'inc/languages/english/ratethread.lang.php.html']
, ['report.lang.php', 'inc/languages/english/report.lang.php.html']
, ['reputation.lang.php', 'inc/languages/english/reputation.lang.php.html']
, ['search.lang.php', 'inc/languages/english/search.lang.php.html']
, ['sendthread.lang.php', 'inc/languages/english/sendthread.lang.php.html']
, ['showteam.lang.php', 'inc/languages/english/showteam.lang.php.html']
, ['showthread.lang.php', 'inc/languages/english/showthread.lang.php.html']
, ['stats.lang.php', 'inc/languages/english/stats.lang.php.html']
, ['syndication.lang.php', 'inc/languages/english/syndication.lang.php.html']
, ['usercp.lang.php', 'inc/languages/english/usercp.lang.php.html']
, ['usercpnav.lang.php', 'inc/languages/english/usercpnav.lang.php.html']
, ['warnings.lang.php', 'inc/languages/english/warnings.lang.php.html']
, ['xmlhttp.lang.php', 'inc/languages/english/xmlhttp.lang.php.html']
]
, ['english.php', 'inc/languages/english.php.html']
, ['index.html', 'inc/languages/index.html.html']
]
, ['mailhandlers', 'inc/mailhandlers/index.html', ['index.html', 'inc/mailhandlers/index.html.html']
, ['php.php', 'inc/mailhandlers/php.php.html']
, ['smtp.php', 'inc/mailhandlers/smtp.php.html']
]
, ['plugins', 'inc/plugins/index.html', ['akismet.php', 'inc/plugins/akismet.php.html']
, ['hello.php', 'inc/plugins/hello.php.html']
, ['index.html', 'inc/plugins/index.html.html']
]
, ['tasks', 'inc/tasks/index.html', ['backupdb.php', 'inc/tasks/backupdb.php.html']
, ['checktables.php', 'inc/tasks/checktables.php.html']
, ['dailycleanup.php', 'inc/tasks/dailycleanup.php.html']
, ['delayedmoderation.php', 'inc/tasks/delayedmoderation.php.html']
, ['hourlycleanup.php', 'inc/tasks/hourlycleanup.php.html']
, ['index.html', 'inc/tasks/index.html.html']
, ['logcleanup.php', 'inc/tasks/logcleanup.php.html']
, ['massmail.php', 'inc/tasks/massmail.php.html']
, ['promotions.php', 'inc/tasks/promotions.php.html']
, ['threadviews.php', 'inc/tasks/threadviews.php.html']
, ['usercleanup.php', 'inc/tasks/usercleanup.php.html']
, ['userpruning.php', 'inc/tasks/userpruning.php.html']
]
, ['adminfunctions_templates.php', 'inc/adminfunctions_templates.php.html']
, ['class_bitwise.php', 'inc/class_bitwise.php.html']
, ['class_captcha.php', 'inc/class_captcha.php.html']
, ['class_core.php', 'inc/class_core.php.html']
, ['class_custommoderation.php', 'inc/class_custommoderation.php.html']
, ['class_datacache.php', 'inc/class_datacache.php.html']
, ['class_error.php', 'inc/class_error.php.html']
, ['class_feedgeneration.php', 'inc/class_feedgeneration.php.html']
, ['class_feedparser.php', 'inc/class_feedparser.php.html']
, ['class_graph.php', 'inc/class_graph.php.html']
, ['class_language.php', 'inc/class_language.php.html']
, ['class_mailhandler.php', 'inc/class_mailhandler.php.html']
, ['class_moderation.php', 'inc/class_moderation.php.html']
, ['class_parser.php', 'inc/class_parser.php.html']
, ['class_plugins.php', 'inc/class_plugins.php.html']
, ['class_session.php', 'inc/class_session.php.html']
, ['class_templates.php', 'inc/class_templates.php.html']
, ['class_timers.php', 'inc/class_timers.php.html']
, ['class_xml.php', 'inc/class_xml.php.html']
, ['config.default.php', 'inc/config.default.php.html']
, ['datahandler.php', 'inc/datahandler.php.html']
, ['db_mysql.php', 'inc/db_mysql.php.html']
, ['db_mysqli.php', 'inc/db_mysqli.php.html']
, ['db_pdo.php', 'inc/db_pdo.php.html']
, ['db_pgsql.php', 'inc/db_pgsql.php.html']
, ['db_sqlite.php', 'inc/db_sqlite.php.html']
, ['functions.php', 'inc/functions.php.html']
, ['functions_archive.php', 'inc/functions_archive.php.html']
, ['functions_calendar.php', 'inc/functions_calendar.php.html']
, ['functions_compat.php', 'inc/functions_compat.php.html']
, ['functions_forumlist.php', 'inc/functions_forumlist.php.html']
, ['functions_image.php', 'inc/functions_image.php.html']
, ['functions_indicators.php', 'inc/functions_indicators.php.html']
, ['functions_massmail.php', 'inc/functions_massmail.php.html']
, ['functions_modcp.php', 'inc/functions_modcp.php.html']
, ['functions_online.php', 'inc/functions_online.php.html']
, ['functions_post.php', 'inc/functions_post.php.html']
, ['functions_posting.php', 'inc/functions_posting.php.html']
, ['functions_rebuild.php', 'inc/functions_rebuild.php.html']
, ['functions_search.php', 'inc/functions_search.php.html']
, ['functions_serverstats.php', 'inc/functions_serverstats.php.html']
, ['functions_task.php', 'inc/functions_task.php.html']
, ['functions_time.php', 'inc/functions_time.php.html']
, ['functions_upload.php', 'inc/functions_upload.php.html']
, ['functions_user.php', 'inc/functions_user.php.html']
, ['functions_warnings.php', 'inc/functions_warnings.php.html']
, ['index.html', 'inc/index.html.html']
, ['init.php', 'inc/init.php.html']
, ['mybb_group.php', 'inc/mybb_group.php.html']
, ['settings.php', 'inc/settings.php.html']
]
, ['install', 'install/index.html', ['images', 'install/images/index.html', ['index.html', 'install/images/index.html.html']
]
, ['resources', 'install/resources/index.html', ['adminoptions.xml', 'install/resources/adminoptions.xml.html']
, ['adminviews.xml', 'install/resources/adminviews.xml.html']
, ['index.html', 'install/resources/index.html.html']
, ['language.lang.php', 'install/resources/language.lang.php.html']
, ['mybb_theme.xml', 'install/resources/mybb_theme.xml.html']
, ['mysql_db_inserts.php', 'install/resources/mysql_db_inserts.php.html']
, ['mysql_db_tables.php', 'install/resources/mysql_db_tables.php.html']
, ['output.php', 'install/resources/output.php.html']
, ['pgsql_db_tables.php', 'install/resources/pgsql_db_tables.php.html']
, ['settings.xml', 'install/resources/settings.xml.html']
, ['sqlite_db_tables.php', 'install/resources/sqlite_db_tables.php.html']
, ['tasks.xml', 'install/resources/tasks.xml.html']
, ['upgrade1.php', 'install/resources/upgrade1.php.html']
, ['upgrade10.php', 'install/resources/upgrade10.php.html']
, ['upgrade11.php', 'install/resources/upgrade11.php.html']
, ['upgrade12.php', 'install/resources/upgrade12.php.html']
, ['upgrade13.php', 'install/resources/upgrade13.php.html']
, ['upgrade14.php', 'install/resources/upgrade14.php.html']
, ['upgrade15.php', 'install/resources/upgrade15.php.html']
, ['upgrade16.php', 'install/resources/upgrade16.php.html']
, ['upgrade17.php', 'install/resources/upgrade17.php.html']
, ['upgrade18.php', 'install/resources/upgrade18.php.html']
, ['upgrade19.php', 'install/resources/upgrade19.php.html']
, ['upgrade2.php', 'install/resources/upgrade2.php.html']
, ['upgrade20.php', 'install/resources/upgrade20.php.html']
, ['upgrade21.php', 'install/resources/upgrade21.php.html']
, ['upgrade22.php', 'install/resources/upgrade22.php.html']
, ['upgrade23.php', 'install/resources/upgrade23.php.html']
, ['upgrade24.php', 'install/resources/upgrade24.php.html']
, ['upgrade3.php', 'install/resources/upgrade3.php.html']
, ['upgrade4.php', 'install/resources/upgrade4.php.html']
, ['upgrade5.php', 'install/resources/upgrade5.php.html']
, ['upgrade6.php', 'install/resources/upgrade6.php.html']
, ['upgrade7.php', 'install/resources/upgrade7.php.html']
, ['upgrade8.php', 'install/resources/upgrade8.php.html']
, ['upgrade9.php', 'install/resources/upgrade9.php.html']
, ['usergroups.xml', 'install/resources/usergroups.xml.html']
]
, ['index.php', 'install/index.php.html']
, ['stylesheet.css', 'install/stylesheet.css.html']
, ['upgrade.php', 'install/upgrade.php.html']
]
, ['jscripts', 'jscripts/index.html', ['editor_themes', 'jscripts/editor_themes/index.html', ['Office_2007', 'jscripts/editor_themes/Office_2007/index.html', ['images', 'jscripts/editor_themes/Office_2007/images/index.html', ['index.html', 'jscripts/editor_themes/Office_2007/images/index.html.html']
]
, ['index.html', 'jscripts/editor_themes/Office_2007/index.html.html']
, ['stylesheet.css', 'jscripts/editor_themes/Office_2007/stylesheet.css.html']
]
, ['default', 'jscripts/editor_themes/default/index.html', ['images', 'jscripts/editor_themes/default/images/index.html', ['index.html', 'jscripts/editor_themes/default/images/index.html.html']
]
, ['index.html', 'jscripts/editor_themes/default/index.html.html']
, ['stylesheet.css', 'jscripts/editor_themes/default/stylesheet.css.html']
]
, ['index.html', 'jscripts/editor_themes/index.html.html']
]
, ['autocomplete.js', 'jscripts/autocomplete.js.html']
, ['captcha.js', 'jscripts/captcha.js.html']
, ['controls.js', 'jscripts/controls.js.html']
, ['dragdrop.js', 'jscripts/dragdrop.js.html']
, ['editor.js', 'jscripts/editor.js.html']
, ['effects.js', 'jscripts/effects.js.html']
, ['general.js', 'jscripts/general.js.html']
, ['index.html', 'jscripts/index.html.html']
, ['inline_edit.js', 'jscripts/inline_edit.js.html']
, ['inline_moderation.js', 'jscripts/inline_moderation.js.html']
, ['popup_menu.js', 'jscripts/popup_menu.js.html']
, ['post.js', 'jscripts/post.js.html']
, ['prototype.js', 'jscripts/prototype.js.html']
, ['rating.js', 'jscripts/rating.js.html']
, ['scriptaculous.js', 'jscripts/scriptaculous.js.html']
, ['slider.js', 'jscripts/slider.js.html']
, ['thread.js', 'jscripts/thread.js.html']
, ['usercp.js', 'jscripts/usercp.js.html']
, ['validator.js', 'jscripts/validator.js.html']
]
, ['uploads', 'uploads/index.html', ['avatars', 'uploads/avatars/index.html', ['index.html', 'uploads/avatars/index.html.html']
]
, ['index.html', 'uploads/index.html.html']
]
, ['announcements.php', 'announcements.php.html']
, ['attachment.php', 'attachment.php.html']
, ['calendar.php', 'calendar.php.html']
, ['captcha.php', 'captcha.php.html']
, ['css.php', 'css.php.html']
, ['editpost.php', 'editpost.php.html']
, ['forumdisplay.php', 'forumdisplay.php.html']
, ['global.php', 'global.php.html']
, ['htaccess.txt', 'htaccess.txt.html']
, ['index.php', 'index.php.html']
, ['managegroup.php', 'managegroup.php.html']
, ['member.php', 'member.php.html']
, ['memberlist.php', 'memberlist.php.html']
, ['misc.php', 'misc.php.html']
, ['modcp.php', 'modcp.php.html']
, ['moderation.php', 'moderation.php.html']
, ['newreply.php', 'newreply.php.html']
, ['newthread.php', 'newthread.php.html']
, ['online.php', 'online.php.html']
, ['polls.php', 'polls.php.html']
, ['portal.php', 'portal.php.html']
, ['printthread.php', 'printthread.php.html']
, ['private.php', 'private.php.html']
, ['ratethread.php', 'ratethread.php.html']
, ['report.php', 'report.php.html']
, ['reputation.php', 'reputation.php.html']
, ['rss.php', 'rss.php.html']
, ['search.php', 'search.php.html']
, ['sendthread.php', 'sendthread.php.html']
, ['showteam.php', 'showteam.php.html']
, ['showthread.php', 'showthread.php.html']
, ['stats.php', 'stats.php.html']
, ['syndication.php', 'syndication.php.html']
, ['task.php', 'task.php.html']
, ['usercp.php', 'usercp.php.html']
, ['usercp2.php', 'usercp2.php.html']
, ['warnings.php', 'warnings.php.html']
, ['xmlhttp.php', 'xmlhttp.php.html']
]
];
